In [ ]:
#create a vector

import numpy as np
vector = np.array([1,2,3,4,5])
print(vector)

[1 2 3 4 5]


In [3]:
#create a matrix

import numpy as np
matrix = np.array([[2,3],[4,5]])
print  ("matrix:", matrix)

matrix: [[2 3]
 [4 5]]


In [4]:
#common operations on vectors

import numpy as np
vector_a =np.array([2,4])
vector_b = np.array([6,9])
vector_c = vector_a + vector_b
print("final vector", vector_c)

final vector [ 8 13]


In [5]:
#common operations on matrices

import numpy as np
matrix_a =np.array([[2,4],[6,7]])
matrix_b =np.array([[6,9],[8,9]])
matrix_c = matrix_a + matrix_b
print ("final matrix", matrix_c)

final matrix [[ 8 13]
 [14 16]]


In [6]:
#scalar multiplication

import numpy as np
vector = np.array([4,5])
scalar = 5
vector_scalar = vector * scalar
print("final vector", vector_scalar)

final vector [20 25]


In [ ]:
#dot product of two vectors is the sum of products of corresponding elements

In [ ]:
#dot product of vector

import numpy as np
vector_a = np.array([2,3])
vector_b = np.array([4,5])
dot_product = np.dot(vector_a, vector_b)
print("final result:", dot_product)

final result: 23


In [10]:
#dot product of matrices

import numpy as np
mat_1 =np.array([[3,4],[5,7]])
mat_2=np.array([[6,7],[8,9]])
dot_product =np.dot(mat_1,mat_2)
mul= mat_1 * mat_2
print ("simple case",mul)

simple case [[18 28]
 [40 63]]


In [11]:
#Transpose of a matrix

import numpy as np
matrix =np.array([[2,3],[4,5]])
transpose =np.transpose(matrix)
transpose1 = matrix.T
print("transpose", transpose1)


transpose [[2 4]
 [3 5]]


In [2]:
# 2x+y=5
# 3x-y = 4

import numpy as np
A= np.array([[2,1],[3,-1]])
B= np.array([5,4])
x,y = np.linalg.solve(A,B)
print("The value of x:",x)
print("The value of y:",y)

The value of x: 1.8
The value of y: 1.4000000000000004


In [ ]:
# Q. Calculate dot product of vector

import numpy as np
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])
dot_product = np.dot(vector_a, vector_b)
print("final result:", dot_product)

final result: 32


In [ ]:
#Q. Calculate dot product of matrices

import numpy as np
mat_1 =np.array([[1,2],[3,4]])
mat_2=np.array([[5,6],[7,8]])
dot_product =np.dot(mat_1,mat_2)
mul= mat_1 * mat_2
print ("simple case",mul)

simple case [[ 5 12]
 [21 32]]


In [ ]:
# Vector Space Concepts 
#1. Set of vectors, 2. Closed under Addition, 3. Closed under Scalar Multiplication, 4. Zero Vector, 5. Additive Inverse
# Dimensions gives a sense of degrees of freedom within the vector space, it's essential for determining the structure and properties of the space.
# Rank of a matrix is essential for solving linear systems, it tells us about the number of independent solutions a system has.
# It also helps in determining whether the system is consistent or over/under constraint.
# Check if the vectors [1,2,3],[4,5,6] and [7,8,9] are linearly independent -> Det[M] = 0 then hence proved.




In [1]:
import numpy as np

m = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

det1 = np.linalg.det(m)

print("result:", det1)

#To be checked again as result should be zero

result: -9.51619735392994e-16


In [6]:
# Linear Transformations

#Q. Apply the linear transformation represented by the matrix: T= [[2,0],[0,3]] to the vector v = [1,1]

import numpy as np
T = np.array([[2,0],[0,3]])
V = np.array([1,1])
TV = T @ V
print("result:",TV)


result: [2 3]


In [ ]:
# Normalize the feature vector v = [3,6,-2] using its manhattan form



In [ ]:
#Practical No. 1
# Vector and matrix operations on traffic data
#Construct mathematical vector and matrix representations from emperical data samples of a city's dailt traffic flow across different intersections, and execute fundamental linear algebraic operations using Python to calculate the total congestion index for each district.

#If a city has intersections and disttricts
#Then we can create
#tarffic vector x: (traffic volume at each intersection)
#District intersection matrix A: (which intersection belong to which district)
#Congestion index vector C: (Total Congestion)

#Solutions: Let x be n x 1 matrix
#Let A be m x n matrix
#Congestion index C = AX
#Let x =[120,80,150] , A = [[1,0,1][0,1,1]]
#C1= 1(120) +0(80)+1(150) = 270
#C2=0(120)+1(80)+1(150) = 230
#C=[270,230]


In [2]:
import numpy as np
#traffic at  3 intersections
x=np.array([120,80,150])
#district intersection mapping
A=np.array([[1,0,1],[0,1,1]])

#Congestion index
C = A@x
print("Traffic Vector:")
print(x)

print("District-Intersection Matrix:")
print(A)

print("Congestion index:")
print(C)

Traffic Vector:
[120  80 150]
District-Intersection Matrix:
[[1 0 1]
 [0 1 1]]
Congestion index:
[270 230]


In [1]:
#Scaling in Linear Transformation

import numpy as np
#scaling matrix
scale_factor = 2
scaling_matrix = np.array([[scale_factor,0],[0,scale_factor]])

#original vector
vector = np.array([1,2])

#applying scaling
scaled_vector = scaling_matrix @ vector
print("scaled vector:", scaled_vector)

scaled vector: [2 4]


In [1]:
#Rotation in linear transformation
import numpy as np
#rotation angle (in radians)
theta=np.pi/4  #45 degree
rotation_matrix=np.array([[np.cos(theta), -np.sin(theta)],[np.sin(theta),np.cos(theta)]])
#original vector
vector=np.array([1,0])
#applying rotation
rotated_vector=rotation_matrix @vector
print("rotated vector",rotated_vector)

rotated vector [0.70710678 0.70710678]


In [2]:
#refelection
import numpy as np
#reflection matrix (y axis)
reflection_matrix=np.array([[1,0],[0,-1]])

#original metrix
vector=np.array([1,2])
#applying reflection
reflected_vector=reflection_matrix@vector
print("reflected vector",reflected_vector)

reflected vector [ 1 -2]


In [ ]:
#Norms are functions that assign strictly positive length or size to each vector in vector space, except for the zero vector which is assigned a length of zero.
#Norms are essential in various fields  as they provide a way to measure distance of vector magnitude.
#Reflection flips the vector over specified axis
#Euclidean(L2) Look into copy for formulae
#Manhattan(L3) Look into copy for formulae
#Infinity(L∞ ) Look into copy for formulae


In [4]:
#Euclidean Norm
import numpy as np
#define the vector
vector =np.array([3,4])

#Calculate the Euclidean norm
norm = np.linalg.norm(vector)
print("Euclidean norm:",norm)

Euclidean norm: 5.0


In [6]:
#Manhattan Norm
import numpy as np
#define the vector
vector =np.array([3,4])

#Calculate the Euclidean norm
norm = np.linalg.norm(vector,ord=1)
print("Manhattan norm:",norm)

Manhattan norm: 7.0


In [7]:
#infinity notm
norm = np.linalg.norm(vector,ord=np.inf)
print("infinity norm:",norm)

infinity norm: 4.0


In [ ]:
#In linear algebra the concept of projection is used to determine the how much of one vector lies in a direction of another vector.

In [2]:
import numpy as np

# Drone position
p = np.array([1, 0])

# Rotation matrix for 90 degrees
theta = np.pi / 2
R = np.array([[np.cos(theta), -np.sin(theta)], 
              [np.sin(theta),  np.cos(theta)]])

# Rotate position
p_rotated = R @ p

print("R:\n", np.round(R, 4))
print("Rotated p:", np.round(p_rotated, 4))


R:
 [[ 0. -1.]
 [ 1.  0.]]
Rotated p: [0. 1.]
