In [1]:
import numpy as np
import tensorflow as tf

In [3]:
s1 = tf.constant(7)
s1

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
v1=tf.constant([10])
v1,v1.ndim

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([10], dtype=int32)>, 1)

In [5]:
m1=tf.constant([[10,7,4],[7,10,13]])
m1,m1.ndim

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10,  7,  4],
        [ 7, 10, 13]], dtype=int32)>,
 2)

In [6]:
m2=tf.constant([[10.5,7],[7,10.1],[8,9]])
m2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.5,  7. ],
       [ 7. , 10.1],
       [ 8. ,  9. ]], dtype=float32)>

In [7]:
#generate a 4D tensor of integers

t4=tf.constant([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[9,10],[11,12]],[[13,14],[15,16]]]])
t4,t4.ndim

(<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
 array([[[[ 1,  2],
          [ 3,  4]],
 
         [[ 5,  6],
          [ 7,  8]]],
 
 
        [[[ 9, 10],
          [11, 12]],
 
         [[13, 14],
          [15, 16]]]], dtype=int32)>,
 4)

In [8]:
t_f=tf.Variable(['b','a','c'])
print(t_f)


<tf.Variable 'Variable:0' shape=(3,) dtype=string, numpy=array([b'b', b'a', b'c'], dtype=object)>


In [9]:
t_f=tf.Variable([True,False])
t_f

<tf.Variable 'Variable:0' shape=(2,) dtype=bool, numpy=array([ True, False])>

In [10]:
t1=tf.constant([1,2,3,4])
print(t1)
print(tf.Variable(t1))

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>


In [11]:
t2d=tf.Variable([[2,31,61],[14,5,8],[53,81,7]])
t2d
tf.argmax(t2d,axis=1)#row wise positions

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 0, 1])>

In [12]:
t2d.assign([[4,5,6],[8,7,8],[32,6,5]])
t2d

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[ 4,  5,  6],
       [ 8,  7,  8],
       [32,  6,  5]], dtype=int32)>

In [13]:
vt=tf.Variable([10,7])
ct=tf.constant([10,7])
vt,ct

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
#creating random tensor

r1=tf.random.Generator.from_seed(3)
r1=r1.normal(shape=(3,2))
print(r1)

tf.Tensor(
[[-0.43640924 -1.9633987 ]
 [-0.06452483 -1.056841  ]
 [ 1.0019137   0.6735137 ]], shape=(3, 2), dtype=float32)


In [1]:
#different seed values (any non-negative integer) affect the random output

import tensorflow as tf
#using seed = 1
gen1=tf.random.Generator.from_seed(1)
print("seed 1:",gen1.normal(shape=[3]))
#Using seed = 42
gen42 = tf.random.Generator.from_seed(42)
print("seed 42:",gen42.normal(shape=[3]))

#Using seed = 123
gen42 = tf.random.Generator.from_seed(123)
print("seed 123:",gen42.normal(shape=[3]))

seed 1: tf.Tensor([ 0.43842274 -0.53439844 -0.07710262], shape=(3,), dtype=float32)
seed 42: tf.Tensor([-0.7565803  -0.06854702  0.07595026], shape=(3,), dtype=float32)
seed 123: tf.Tensor([ 0.8673864  -0.29899067 -0.9310337 ], shape=(3,), dtype=float32)
