In [21]:
import numpy as np
import tensorflow as tf

In [2]:
s1 = tf.constant(7)
s1

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
v1=tf.constant([10])
v1,v1.ndim

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([10], dtype=int32)>, 1)

In [4]:
m1=tf.constant([[10,7,4],[7,10,13]])
m1,m1.ndim

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10,  7,  4],
        [ 7, 10, 13]], dtype=int32)>,
 2)

In [5]:
m2=tf.constant([[10.5,7],[7,10.1],[8,9]])
m2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.5,  7. ],
       [ 7. , 10.1],
       [ 8. ,  9. ]], dtype=float32)>

In [6]:
#generate a 4D tensor of integers

t4=tf.constant([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[9,10],[11,12]],[[13,14],[15,16]]]])
t4,t4.ndim

(<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
 array([[[[ 1,  2],
          [ 3,  4]],
 
         [[ 5,  6],
          [ 7,  8]]],
 
 
        [[[ 9, 10],
          [11, 12]],
 
         [[13, 14],
          [15, 16]]]], dtype=int32)>,
 4)

In [7]:
t_f=tf.Variable(['b','a','c'])
print(t_f)


<tf.Variable 'Variable:0' shape=(3,) dtype=string, numpy=array([b'b', b'a', b'c'], dtype=object)>


In [8]:
t_f=tf.Variable([True,False])
t_f

<tf.Variable 'Variable:0' shape=(2,) dtype=bool, numpy=array([ True, False])>

In [9]:
t1=tf.constant([1,2,3,4])
print(t1)
print(tf.Variable(t1))

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>


In [10]:
t2d=tf.Variable([[2,31,61],[14,5,8],[53,81,7]])
t2d
tf.argmax(t2d,axis=1)#row wise positions

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 0, 1])>

In [11]:
t2d.assign([[4,5,6],[8,7,8],[32,6,5]])
t2d

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[ 4,  5,  6],
       [ 8,  7,  8],
       [32,  6,  5]], dtype=int32)>

In [12]:
vt=tf.Variable([10,7])
ct=tf.constant([10,7])
vt,ct

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
#creating random tensor

r1=tf.random.Generator.from_seed(3)
r1=r1.normal(shape=(3,2))
print(r1)

tf.Tensor(
[[-0.43640924 -1.9633987 ]
 [-0.06452483 -1.056841  ]
 [ 1.0019137   0.6735137 ]], shape=(3, 2), dtype=float32)


In [14]:
#different seed values (any non-negative integer) affect the random output

import tensorflow as tf
#using seed = 1
gen1=tf.random.Generator.from_seed(1)
print("seed 1:",gen1.normal(shape=[3]))
#Using seed = 42
gen42 = tf.random.Generator.from_seed(42)
print("seed 42:",gen42.normal(shape=[3]))

#Using seed = 123
gen42 = tf.random.Generator.from_seed(123)
print("seed 123:",gen42.normal(shape=[3]))

seed 1: tf.Tensor([ 0.43842274 -0.53439844 -0.07710262], shape=(3,), dtype=float32)
seed 42: tf.Tensor([-0.7565803  -0.06854702  0.07595026], shape=(3,), dtype=float32)
seed 123: tf.Tensor([ 0.8673864  -0.29899067 -0.9310337 ], shape=(3,), dtype=float32)


In [15]:
n1 = tf.constant([[10,7],[3,4],[2,5]])
n1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [16]:
tf.random.shuffle (n1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [17]:
tf.ones(shape=(4,2)), tf.zeros(shape=(3,2))

(<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=float32)>)

In [18]:
vector_tensor = tf.constant([1,2,3,4])
print(vector_tensor)
vector_tensor.ndim


tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


1

In [19]:
#Define Matrix Tensor

matrix_tensor =tf.constant([[1,2],[3,4]])
print(matrix_tensor)

#Define a ones tensor creates a tensor of all ones that has the same shape as the input
ones_tensor=tf.ones_like(matrix_tensor)
print(ones_tensor)

#Element wise addition
tensor_add =tf.add(matrix_tensor,ones_tensor)
print(tensor_add)

#Matrix multiplication (dot product)

matrix_mult =tf.matmul(matrix_tensor,matrix_tensor)

print(matrix_mult)



tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)


In [24]:
import tensorflow as tf
r4t = tf.zeros(shape=[2, 3, 4, 5])
print(r4t)
r1 = tf.zeros(shape=[3, 2])
print(r1)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [25]:
print(r4t.shape[0])
print(r4t.shape[-1])

2
5


In [26]:
r2t=tf.constant([[10,7],[3,4]])
print(r2t)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [27]:
tf.newaxis()
r3t=r2t[:,:,tf.newaxis] #adds a new dimension at the end, changing (2,2)->(2,2,1)
print(r3t)

TypeError: 'NoneType' object is not callable

In [28]:
tf.expand_dim(r2t,axis=-1) #add one new dimension at the end of the tensor. Here axis=-1 means ....

AttributeError: module 'tensorflow' has no attribute 'expand_dim'

In [29]:
tf.expand_dims(r2t,axis=1)


<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [30]:
#Manipulating Tensor Basic Operations
t1=tf.constant([[10,7],[3,4]])
print(t1 + 10)
print(t1 - 10)
print(t1 * 10)
print(t1 / 10)

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 0 -3]
 [-7 -6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1.  0.7]
 [0.3 0.4]], shape=(2, 2), dtype=float64)


In [31]:
#Builtin functions for operations
t=tf.multiply([[10,7],[3,4]])
print(t)

TypeError: Missing required positional argument

In [32]:
#Matrix multiplicatiion
t=tf.constant([[10,7],[3,4]])
print(t)


tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [33]:
t=tf.constant([[1,2,5],[7,2,1]])
t1=tf.constant([[3,5],[6,7]])
print(tf.matmul(t,tf.reshape(t,shape=(3,2))))


tf.Tensor(
[[21 21]
 [19 29]], shape=(2, 2), dtype=int32)


In [34]:
#Transpose

x=tf.constant([[1,2],[3,4],[5,6]])
y=tf.constant([[7,8],[9,10],[11,12]])
print(tf.transpose(x))

tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)


In [35]:
z=tf.transpose(x)
print(tf.tensordot(z,y, axis=0))

TypeError: Got an unexpected keyword argument 'axis'

In [36]:
#Mixed precision => float16 runs faster than float32; Update datatype as:

d=tf.constant([10,7]), dtype=tf.float(6)
d,d.dtype

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (1093817573.py, line 3)

In [37]:
#Change from int32 to float32

E=tf.cast(c,dtype=tf.float32)
E

NameError: name 'c' is not defined

In [38]:
#Get absolute values
D=tf.constant .....

SyntaxError: invalid syntax (427493582.py, line 2)

In [ ]:
#Forms of aggre